### ISSUE TITLE
Crash when accessing settings using Mod Menu

### ISSUE THREAD

**Issue by RealCea** [CaelTheColher/Capes#57] opened 2022-06-21 19:26 UTC
**Describe the bug**
I crash whenever I click on the Mod Menu settings button for the mod.

**To Reproduce**
1. Go to 'Mods' using Mod Menu mod
2. Click on the Capes mod
3. Click the settings button in the top-right

**Expected behavior**
The standard settings menu for what should be there

**Context:**
 - Minecraft version: 1.19
 - Capes version: 1.4.2
 - Mod list:
 - Mods that might cause issues:
 *3DSkinLayers, DynamicFPS, Ears, EnhancedBlockEntities, EntityCulling, Indium, 
 Iris, LazyDFU, Lithium, ModMenu, NotEnoughAnimations, Sodium, StarLight, 
 WavyCapes*
 - Mod that probably won't cause issues:
 *AppleSkin, AxolotolItemFix, BoostedBrightness, Clickthrough, Continuity, EatingAnimation, Effective, FabricKotlinLanguage, 
 FirstPersonModel, Illuminations, InventoryProfilesNext, JourneyMap, LambdaBetterGrass, LambDynamicLights, LogicalZoom, NamePain, Visuality*
 - Server: N/A

**Crash Report:**
*The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_19538()" because "$$0" is null
Exit Code: -1*

**Comment by CaelTheColher** [comment] 2022-06-21 20:19
Crash seems to be caused by 3d skin layers, I'm currently investigating

**Comment by CaelTheColher** [comment] 2022-06-21 20:45
Should be fixed in the next version.

**Closed by CaelTheColher** 2022-06-21 20:45 UTC
